import{a as c,S as f,i as d}from"./assets/vendor-b2578120.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&t(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();c.create({baseURL:"https://pixabay.com/api/",params:{key:"43015885-c3997a91f23585149f1baaf72",q:i,image_type:"photo",orientation:"horizontal",safesearch:"true"}});async function m(){const s="https://pixabay.com/api/",o=new URLSearchParams({key:"43015885-c3997a91f23585149f1baaf72",q:i,image_type:"photo",orientation:"horizontal",safesearch:"true"}),n=`${s}?${o}`;return h(),(await c.get(n)).data}function y(s){if(s.hits.length===0)u("Sorry, there are no images matching your search query. Please try again!");else{a.gallery.innerHTML="";const n=s.hits.map(t=>`<li class="gallery-item">
                <a class="gallery-link" href="${t.largeImageURL}">
                <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}" />
                </a>
                <div class="stats">
                    <p class="text">Likes<br/>${t.likes}</p>
                    <p class="text">Views<br/>${t.views}</p>
                    <p class="text">Comments<br/>${t.comments}</p>
                    <p class="text">Downloads<br/>${t.downloads}</p>
                </div>
            </li>`).join("");a.gallery.insertAdjacentHTML("beforeend",n),g.refresh()}}const g=new f(".gallery-link",{captionsData:"alt",captionDelay:250}),a={form:document.querySelector(".form"),searchInput:document.getElementById("searchInput"),searchBtn:document.querySelector("button"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery")};p();let i="";a.form.addEventListener("submit",s=>{s.preventDefault(),a.gallery.innerHTML="",i=a.searchInput.value.trim(),i!==""?m().then(o=>{y(o),p()}).catch(o=>console.log(o)):u("Empty field!"),a.form.reset()});function u(s){d.error({title:"Error",message:s,position:"topRight",backgroundColor:"red"})}function p(){a.loader.style.display="none"}function h(){a.loader.style.display="block"}
//# sourceMappingURL=commonHelpers.js.map
