import{a as d,S as f,i as p}from"./assets/vendor-b2578120.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const y=d.create({baseURL:"https://pixabay.com/api/"});async function m(){const s={key:"43015885-c3997a91f23585149f1baaf72",q:n,image_type:"photo",orientation:"horizontal",safesearch:"true"};return b(),(await y.get("",{params:s})).data}function g(s){if(s.hits.length===0)c("Sorry, there are no images matching your search query. Please try again!");else{a.gallery.innerHTML="";const i=s.hits.map(r=>`<li class="gallery-item">
                <a class="gallery-link" href="${r.largeImageURL}">
                <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
                </a>
                <div class="stats">
                    <p class="text">Likes<br/>${r.likes}</p>
                    <p class="text">Views<br/>${r.views}</p>
                    <p class="text">Comments<br/>${r.comments}</p>
                    <p class="text">Downloads<br/>${r.downloads}</p>
                </div>
            </li>`).join("");a.gallery.insertAdjacentHTML("beforeend",i),h.refresh()}}const h=new f(".gallery-link",{captionsData:"alt",captionDelay:250}),a={form:document.querySelector(".form"),searchInput:document.getElementById("searchInput"),searchBtn:document.querySelector("button"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery")};u();let n="";a.form.addEventListener("submit",async s=>{if(s.preventDefault(),a.gallery.innerHTML="",n=a.searchInput.value.trim(),n!=="")try{const o=await m(n);g(o),u()}catch(o){console.log(o)}else c("Empty field!");a.form.reset()});function c(s){p.error({title:"Error",message:s,position:"topRight",backgroundColor:"red"})}function u(){a.loader.style.display="none"}function b(){a.loader.style.display="block"}
//# sourceMappingURL=commonHelpers.js.map
