import{a as h,S as b,i as L}from"./assets/vendor-b2578120.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const w=h.create({baseURL:"https://pixabay.com/api/"});async function f(){const s={key:"43015885-c3997a91f23585149f1baaf72",q:i,per_page:u,page:l,image_type:"photo",orientation:"horizontal",safesearch:"true"};return q(),(await w.get("",{params:s})).data}function m(s){if(s.hits.length===0)y("Sorry, there are no images matching your search query. Please try again!");else{const n=s.hits.map(o=>`<li class="gallery-item">
                <a class="gallery-link" href="${o.largeImageURL}">
                <img loading="lazy" class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
                </a>
                <div class="stats">
                    <p class="text">Likes<br/>${o.likes}</p>
                    <p class="text">Views<br/>${o.views}</p>
                    <p class="text">Comments<br/>${o.comments}</p>
                    <p class="text">Downloads<br/>${o.downloads}</p>
                </div>
            </li>`).join("");a.gallery.insertAdjacentHTML("beforeend",n),v.refresh()}}const v=new b(".gallery-link",{captionsData:"alt",captionDelay:250}),a={form:document.querySelector(".form"),searchInput:document.getElementById("searchInput"),searchBtn:document.querySelector("button"),loadBtn:document.querySelector(".load-more-button"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery")};let i="",l=1,u=15;c();p();a.form.addEventListener("submit",async s=>{if(s.preventDefault(),l=1,a.gallery.innerHTML="",i=a.searchInput.value.trim(),i!=="")try{const t=await f(i,l),n=Math.ceil(t.totalHits/u);m(t),c(),g()}catch(t){console.log(t)}else y("Empty field!"),p();a.form.reset()});a.loadBtn.addEventListener("click",async s=>{l+=1;const t=await f();c(),m(t),g();const o=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o.height*2,behavior:"smooth"}),l>u&&(y("We're sorry, but you've reached the end of search results."),p(),c())});function y(s){L.error({title:"Error",message:s,position:"topRight",backgroundColor:"red"})}function c(){a.loader.style.display="none"}function q(){a.loader.style.display="block"}function p(){a.loadBtn.style.display="none"}function g(){a.loadBtn.style.display="block"}
//# sourceMappingURL=commonHelpers.js.map
